name: eis

services:
    elact-docs:
        image: eis
        env_file: .env
        environment:
            - NODEID=eis.elact-docs
            - SERVICES=elact-docs.service.mjs
            - DOPPLER_TOKEN

    elact-utils:
        image: eis
        env_file: .env
        environment:
            - NODEID=eis.elact-utils
            - SERVICES=elact-utils.service.mjs
            - DOPPLER_TOKEN

    zakupki-rss:
        image: eis
        env_file: .env
        environment:
            - NODEID=eis.zakupki-rss
            - SERVICES=zakupki-rss.service.mjs
            - DOPPLER_TOKEN

    elact-eruz:
        image: eis
        env_file: .env
        environment:
            - NODEID=eis.elact-eruz
            - SERVICES=elact-eruz.service.mjs
            - DOPPLER_TOKEN
        volumes:
            - ./database:/usr/src/app/database:rw
